export const DESCRIPTION = 'CV + AI = Offer in 2026'

export const KEYWORDS = [
	'resume builder',
	'cv generator',
	'resume maker',
	'curriculum vitae',
	'professional resume',
	'resume template',
	'cover letter generator',
	'ats-friendly resume',
	'instant resume',
	'quick cv builder',
	'resume in minutes',
	'auto-fill resume',
	'one-click resume',
	'fast resume creation',
	'automated cv',
	'ai resume builder',
	'ai-powered cv',
	'gpt resume',
	'ai career tools',
	'smart resume',
	'ai job application',
	'generative ai',
	'job application',
	'career tools',
	'ats optimization',
	'applicant tracking system',
	'keyword optimization',
	'job matching',
	'customizable template',
	'free resume builder',
	'land more interviews',
	'resume saas',
	'career platform',
	'online resume builder',
	'hr tech',
	'career tech'
]
